const main = async () => {
  console.log("main servr")
}

main().catch((err) => console.log(err))
